language: objective-c
osx_image: xcode8
sudo: false
notifications:
  email: false
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - git clone https://github.com/phacility/arcanist.git
  - git clone https://github.com/phacility/libphutil.git
  - pod install
script:
  - set -o pipefail
  - arcanist/bin/arc unit --everything
  - xcodebuild build -workspace MaterialMotionRuntime.xcworkspace -scheme Catalog -sdk "iphonesimulator10.0" -destination "name=iPhone 6s,OS=10.0" ONLY_ACTIVE_ARCH=YES | xcpretty -c;
